routes/web.php
<?php

use App\Http\Controllers\AppointmentController;
use App\Http\Controllers\PatientController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ProcedureController;
use App\Http\Controllers\RequestApprovalController;
use App\Http\Controllers\ReportsController;
use App\Http\Controllers\TreatmentController;
use App\Http\Controllers\DashController;
use App\Http\Controllers\AdminDashController;
use Illuminate\Http\Request;
use App\Models\ProcedureCategory;
use App\Models\Treatment;
use App\Models\Patient;
use App\Models\Procedure;
use App\Models\Payment;
use App\Models\Appointment;
use Illuminate\Support\Facades\DB;

use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
    return redirect('/online-appointment');
});

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/dashboard', function () {
    echo Auth::user;
});

Route::get('/log', function () {
    return view('login');
});

// User routes
Route::group(['middleware' => ['auth', 'admin']], function () {
    Route::get('/users', function () {
        return view('user.index');
    });
    Route::get('/users/index', [UserController::class, 'index']);
    Route::post('/users/store', [UserController::class, 'store']);
    Route::post('/users/destroy', [UserController::class, 'destroy']);
    Route::get('/users/{id}/show', [UserController::class, 'show']);
    Route::post('/users/update', [UserController::class, 'update']);
    Route::post('/users/search', [UserController::class, 'search']);
});

Route::get('/reports', function () {
    return view('reports.index');
});
Route::get('/dashboard/admin', function () {
    return view('/admindash.index');
});

Route::group(['middleware' => ['auth', 'dentist']], function () {
    Route::post('/appointments/store', [AppointmentController::class, 'store']);
    
    Route::get('/appointment/index', [AppointmentController::class, 'index']);
    Route::post('/appointments/update', [AppointmentController::class, 'update']);
    Route::post('/appointments/delete', [AppointmentController::class, 'destroy']);
    Route::post('/appointments/request-approval/accept', [AppointmentController::class, 'requestApprovalAccept']);
    Route::post('/appointments/request-approval/reject', [AppointmentController::class, 'requestApprovalReject']);
    Route::post('/appointments/request-approval/review/accept', [AppointmentController::class, 'requestApprovalReviewAccept']);

    Route::get('/dashboard/dentist', function () {
        return view('dentistdash.index');
    });
    // Payment routes
    Route::get('/payments', function () {
        return view('payment.index');
    });
});

// Appointment routes
Route::get('/appointments', function () {
    return view('appointment.index');
});
Route::get('/events', [AppointmentController::class, 'events']);
Route::get('/event/{id}', [AppointmentController::class, 'getEventById']);
Route::get('/appointments/request-approval', function () {
    return view('appointment.request-approval');
});
Route::post('/appointments/search', [AppointmentController::class, 'search']);

Route::group(['middleware' => ['auth', 'receptionist']], function () {
    Route::get('/payments/logs/index', [PaymentController::class, 'logs']);
    Route::post('/payments/update', [PaymentController::class, 'update']);
    Route::get('/payments/logs', function() {
        return view('payment.logs');
    });
});



// data for table
Route::get('/userData', [UserController::class, 'getData']);
Route::get('/logsData', [PaymentController::class, 'getLogs']);
Route::get('/treatmentData', [TreatmentController::class, 'getData']);
Route::get('/paymentData', [PaymentController::class, 'getData']);

Route::group(['middleware' => ['auth']], function () {
    // Treatment routes
    Route::get('/treatments', function () {
        return view('treatment.index');
    });
  
    Route::get('/treatments/index', [TreatmentController::class, 'index']);
    Route::post('/treatments/{tooth}/{procid}/{cost}/{date}/{patientid}/save', [TreatmentController::class, 'saveMulti']);
    Route::get('/treatments/{toothno}/{procid}/{cost}/{date}/{id}/save', [TreatmentController::class, 'savemulti']);
    Route::get('/treatments/{id}/show', [TreatmentController::class, 'show']);
    Route::get('/treatments/{id}/procedures', [TreatmentController::class, 'showSelectedProcedures']);
    Route::post('/treatments', [TreatmentController::class, 'saveProcedure']);
    Route::post('/treatments/update', [TreatmentController::class, 'update']);
    Route::post('/treatments/delete', [TreatmentController::class, 'destroy']);
    Route::post('/treatments/search', [TreatmentController::class, 'search']);
    Route::post('/treatments/store', [TreatmentController::class, 'store']);
    Route::get('/treatments/{id}/getProcedures', [TreatmentController::class, 'getProceduresByTreatmentId']);
    Route::get('/treatments/{patient_id}/{tooth_number}/getTreatments', [TreatmentController::class, 'getTreatmentsByPatientId']);
});

// Payments routes
Route::get('/payments/index', [PaymentController::class, 'index']);
Route::post('/payments/store', [PaymentController::class, 'store']);
Route::post('/payments/delete', [PaymentController::class, 'destroy']);
Route::get('/payments/{id}/show', [PaymentController::class, 'show']);

// Appointment request routes
Route::get('/old-appointment-requests', [RequestApprovalController::class, 'oldAppointmentRequests']);
Route::get('/new-appointment-requests', [RequestApprovalController::class, 'newAppointmentRequests']);
Route::post('/appointment-requests/store', [RequestApprovalController::class, 'store']);

// Patient routes

Route::get('/getInactive', [PatientController::class, 'getInactive']);
Route::get('/getPatientData', [PatientController::class, 'getData']);
Route::get('/patients', function () {
    return view('patient.index');
});
Route::post('/patients/store', [PatientController::class, 'store']);
Route::get('/patients/{status}', [PatientController::class, 'patients']);
Route::get('/inactive-patients', function () {
    return view('patient.inactive-patients');
});
// Route::get('/patients/inactive', [PatientController::class, 'inactivePatients']);
Route::get('/patients/{id}/appointments', [PatientController::class, 'appointments']);
Route::get('/get-patient/{id}', [PatientController::class, 'show']);
Route::get('/get-patient-with-appointments/{id}', [PatientController::class, 'showPatientWithAppointments']);
Route::post('/patients/update', [PatientController::class, 'update']);
Route::post('/patients/deactivate', [PatientController::class, 'deactivatePatient']);
Route::post('/patients/activate', [PatientController::class, 'activatePatient']);
Route::post('/patients/search', [PatientController::class, 'search']);

// Procedure routes
Route::get('/procedures/index', [ProcedureController::class, 'index']);

// Website and Online Appointment routes
Route::get('/online-appointment/{date}/schedules', [AppointmentController::class, 'getAppointmentsByDate']);
Route::get('/online-appointment', function () {
    return view('online-appointment.index2');
});
Route::get('/online-appointment/patient-type', function () {
    return view('online-appointment.patient-type');
});
Route::get('/online-appointment/new-patient-form', function () {
    return view('online-appointment.new-patient-form');
});
Route::get('/online-appointment/old-patient-form', [PatientController::class, 'getPatientBySlug']);
Route::get('/online-appointment/new-patient-form', [AppointmentController::class, 'newPatientForm']);
Route::get('/online-appointment/new-patient-form/check-email-availability/{email}', [AppointmentController::class, 'checkEmailAvailability']);
Route::get('/online-appointment/new-patient-form/update/{referenceId}', [AppointmentController::class, 'updateNewPatientAppointmentGet']);
Route::post('/online-appointment/new-patient-form/update', [AppointmentController::class, 'updateNewPatientAppointmentPost']);
Route::post('/online-appointment/submit', [AppointmentController::class, 'onlineAppointmentSubmit']);
Route::post('/online-appointment/cancel-appointment', [AppointmentController::class, 'cancelAppointment']);
Route::get('/online-appointment/confirm/{reference_id}/{patient_type}', [AppointmentController::class, 'confirmAppointment']);

Route::get('/landing', function () {
    return view('online.landingpage');
});
Route::get('/get-patient-by-slug', [PatientController::class, 'getPatientBySlug']);

// Test routings
Route::get('/tests', function (Request $request) {
    $old = DB::table('old_patient_appointment_requests')->where('reference_id', '7OQwN')->first();

    print_r(json_encode($old) );

});

//dashboard routings
Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {

    switch(Auth::user()->user_role_id){
        case 1:
            return redirect('dashboard/admin');
            break;
        case 2:
            return redirect('dashboard/admin');
            break;
        case 3:
            return redirect('dashboard/dentist');
            break;
        case 4:
            return redirect('dashboard/receptionist');
            break;
    }
})->name('dashboard');
Route::get('dashboard/admin', [DashController::class, 'getAdminDashData']);
Route::get('dashboard/receptionist', [DashController::class, 'getReceptionistDashData']);
Route::get('dashboard/dentist', [DashController::class, 'getTodaysAppointmentData']);
//end of dashboard routings

    // return json_encode($result);

// });

//reports

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title inertia>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <!-- <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap"> -->

        <!-- Styles -->
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">

        <!-- Scripts -->
        @routes
        <script src="{{ mix('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        @inertia

        @env ('local')
            <script src="http://localhost:3000/browser-sync/browser-sync-client.js"></script>
        @endenv
    </body>
</html>

resources/views/dashboard-main.blade.php
@extends('master')
@section('title', 'Gabrillo Dental Clinic')
@section('content')
<div id="content">
@include('dashboard.index')
</div>
@endsection

resources/views/index.blade.php
@if (Auth::check())
    @extends('master')
    @section('title', 'Gabrillo Dental Clinic')
    @section('content')
    <div id="content">
    @include('dashboard.index')
    </div>
    @endsection     
@else
    <script>window.location = "/login";</script>
@endif

resources/views/login.blade.php
<html>

<head>

    <link rel="stylesheet" href="{{ asset('css/login.css')}}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />

    <title>Gabrillo Dental Clinic</title>

</head>

<body>
    <nav class="navbar navbar-light fixed-top">
        <a class="navbar-brand"><img src="{{ asset('img/logo-desk.png')}}" alt="logo" width="45px">
            <b class="navtitle">GABRILLO DENTAL CLINIC</b>
        </a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
                <li>
                    <a class="color-me" href="#aboutus"><b>ABOUT US</b></a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="conform rounded boarder-info justify-content-start">
        <div style="margin-left: 20px;margin-right: 20px">
            <div class="row" style="margin-top: 30px;">
                <div class="col-lg">
                    <h2 class="title text-dark">WELCOME TO GABRILLO DENTAL CLINIC</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-lg">
                    <form method="POST" action="/login">
                        @csrf
                        <div class="form-group">
                            <label for="label formGroupExampleInput">Username</label>
                            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Enter username">
                        </div>
                        <div class="form-group">
                            <label for="label formGroupExampleInput2">Password</label>
                            <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Enter password">
                        </div>
                        <div style="margin-left: 41%; margin-top: 30%">
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    <!--
<img class="vector1" src="/images/Asset 1.svg" alt="svg">
<img class="svg1" src="/images/LGroupM.svg" alt="svg">
<img class="svg2" src="/images/BIgC.svg" alt="">
-->

    <img class="try" src="{{ asset('img/doctor.svg') }}" alt="">
    <img class="svg2" src="{{ asset('img/BIgC.svg') }}" alt="">

</body>

</html>

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title> @yield('title') </title>

    <link href="{{ asset('css/styles.css') }}" rel="stylesheet">
    <link href="{{ asset('css/treatment.css') }}" rel="stylesheet">
    <link href="{{ asset('css/calendar.css') }}" rel="stylesheet">
    <link href="{{ asset('css/dashboard.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/request-approval.css') }}" rel="stylesheet">
    <link href="{{ asset('css/admindash.css') }}" rel="stylesheet">

    <link rel="stylesheet" href="{{ asset('css/tooth-numbering.css') }}">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ asset('/apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('img/favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('img/favicon-16x16.png') }} ">
    <link rel="mask-icon" href="{{ asset('/safari-pinned-tab.svg') }}" color="#5bbad5">
    <link rel="manifest" href="{{ asset('/site.webmanifest') }}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/main.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel='stylesheet' href='https://unpkg.com/carbon-components@latest/css/carbon-components.css'>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    

<!-- Dentist dash-->
<!-- <link rel="stylesheet" type="text/css" href="{{ url('/css/dentist-style.css') }}" /> 
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" type="text/css" href="{{ url('/css/calendar-dentist.css') }}" />
 <link
 rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css"
    /> -->


    <!-- datepicker -->
    <link href="http://code.jquery.com/ui/1.9.2/themes/smoothness/jquery-ui.css" rel="stylesheet" />

    <!--date picker -->
    <script src="http://code.jquery.com/jquery-1.8.3.min.js"></script>
    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>

    <!-- Sweet alert -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js"
        integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous">                                                            
    </script>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script> -->


    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <!-- <script src="https://netdna.bootstrapcdn.com/bootstrap/2.3.2/js/bootstrap.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.2.0/js/bootstrap-datepicker.min.js"></script>

    <script src="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.css"> 


    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/main.min.js"></script>                                                                                                 

    <script src="{{ asset('js/index.js') }}"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.5/umd/popper.js"></script> -->
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.5/umd/popper.min.js"></script> -->
    <!-- <link href="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.css" rel="stylesheet"> -->



    <script src="https://cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>

<body>
@include('shared.main-nav')
@if ($errors->any())
<div class="msg mb-5 auto-hide alert-danger" style="position: fixed; bottom: 0; right: 0; z-index: 9999;">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
</div>
@endif

@if (session('err'))
<div class="msg mb-5 auto-hide alert-danger" style="position: fixed; bottom: 0; right: 0; z-index: 9999;">
    {{ session('err') }}
</div>
<!-- <div class="alert alert-success">
</div> -->
    @endif

    @if (session('status'))
        <div class="msg mb-5 auto-hide" style="position: fixed; bottom: 0; right: 0; z-index: 9999;">
            {{ session('status') }}
        </div>
        <!-- <div class="alert alert-success">
</div> -->
    @endif
    <img class="mx-auto" id="loading" src="{{ asset('img/spinner-logo.png') }}" width="120" height="80" alt="logo">
    @yield('content')
</body>

</html>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/spinner.blade.php
<img id="loading" src="{{ asset('img/spinner-logo.png') }}" width="120" height="80" alt="logo">

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>